apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-app
  namespace: argocd
spec:
  project: apps-of-apps
  source:
    repoURL: https://github.com/jarin-ni/apps-of-apps
    targetRevision: main
    path: staging/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

