apiVersion: v1
kind: Service
metadata:
  name: nginx-staging-apps
  namespace: 
spec:
  selector:
    app.kubernetes.io/name: staging
    app.kubernetes.io/instance: staging-apps
  ports:
  - port: 80
    targetPort: 80
