apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-staging-apps
  namespace: staging
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: staging-apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/instance: staging-apps
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/instance: staging-apps
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
