apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-app
  namespace: argocd
spec:
  project: apps-of-app
  source:
    repoURL: https://github.com/jarin-ni/apps-of-apps
    targetRevision: main
    path: prod/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

