apiVersion: v1
kind: Service
metadata:
  name: nginx-prod-apps
  namespace: prod
spec:
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: prod-apps
  ports:
  - port: 80
    targetPort: 80

