apiVersion: v1
kind: Service
metadata:
  name: nginx-dev-apps
  namespace: dev
spec:
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: dev-apps
  ports:
  - port: 80
    targetPort: 80
